[project]
name = "repo-b"
version = "0.0.0"

[tool.commitizen]
name = "cz_customize"
version_provider = "commitizen"
update_changelog_on_bump = true
changelog_incremental = true

[tool.commitizen.customize]
changelog_pattern = "^(feat|fix)\\(repo-b(\\.\\w+)*\\)(!)?:"