[project]
name = "repo-a"
version = "0.0.0"

[tool.commitizen]
name = "cz_customize"
version_provider = "pep621"
update_changelog_on_bump = true
changelog_incremental = true

[tool.commitizen.customize]
changelog_pattern = "^(feat|fix)\\(repo-a(\\.\\w+)*\\)(!)?:"

