[project]
name = "repo-a"
version = "1.1.0"

[tool.commitizen]
name = "cz_customize"
version = "0.0.0"
tag_format = "${version}"
update_changelog_on_bump = true

[tool.commitizen.customize]
changelog_pattern = "^(feat|fix)\\(library-b\\)(!)?:"